// Wire format for collector <-> collector query fan-out.
//
// A coordinator parses and plans a query once, then ships each owning peer the
// planned logs statement with that peer's stream ids already bound. The peer
// never sees DSL text and never plans: it checks the statement against the
// planner's identifier allow-list, runs it, and streams the rows back. Shipping
// the plan rather than the text means a parse error surfaces exactly once, on
// the coordinator, and every peer executes the same SQL.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: logagg/v1/cluster.proto

package logaggv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Arg is one bound parameter of a planned statement. The cases mirror the Go
// types the planner mints; anything else is a planner change and a wire change.
type Arg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Arg_Text
	//	*Arg_Integer
	//	*Arg_Level
	//	*Arg_Number
	//	*Arg_TimeUnixNano
	//	*Arg_DurationNanos
	//	*Arg_StreamIds
	Value         isArg_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Arg) Reset() {
	*x = Arg{}
	mi := &file_logagg_v1_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Arg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Arg) ProtoMessage() {}

func (x *Arg) ProtoReflect() protoreflect.Message {
	mi := &file_logagg_v1_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Arg.ProtoReflect.Descriptor instead.
func (*Arg) Descriptor() ([]byte, []int) {
	return file_logagg_v1_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *Arg) GetValue() isArg_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Arg) GetText() string {
	if x != nil {
		if x, ok := x.Value.(*Arg_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *Arg) GetInteger() int64 {
	if x != nil {
		if x, ok := x.Value.(*Arg_Integer); ok {
			return x.Integer
		}
	}
	return 0
}

func (x *Arg) GetLevel() int32 {
	if x != nil {
		if x, ok := x.Value.(*Arg_Level); ok {
			return x.Level
		}
	}
	return 0
}

func (x *Arg) GetNumber() float64 {
	if x != nil {
		if x, ok := x.Value.(*Arg_Number); ok {
			return x.Number
		}
	}
	return 0
}

func (x *Arg) GetTimeUnixNano() int64 {
	if x != nil {
		if x, ok := x.Value.(*Arg_TimeUnixNano); ok {
			return x.TimeUnixNano
		}
	}
	return 0
}

func (x *Arg) GetDurationNanos() int64 {
	if x != nil {
		if x, ok := x.Value.(*Arg_DurationNanos); ok {
			return x.DurationNanos
		}
	}
	return 0
}

func (x *Arg) GetStreamIds() *StreamIDs {
	if x != nil {
		if x, ok := x.Value.(*Arg_StreamIds); ok {
			return x.StreamIds
		}
	}
	return nil
}

type isArg_Value interface {
	isArg_Value()
}

type Arg_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type Arg_Integer struct {
	Integer int64 `protobuf:"varint,2,opt,name=integer,proto3,oneof"`
}

type Arg_Level struct {
	// level is the smallint column; kept apart from integer so the peer binds
	// the type Postgres expects without a cast.
	Level int32 `protobuf:"varint,3,opt,name=level,proto3,oneof"`
}

type Arg_Number struct {
	Number float64 `protobuf:"fixed64,4,opt,name=number,proto3,oneof"`
}

type Arg_TimeUnixNano struct {
	TimeUnixNano int64 `protobuf:"varint,5,opt,name=time_unix_nano,json=timeUnixNano,proto3,oneof"`
}

type Arg_DurationNanos struct {
	DurationNanos int64 `protobuf:"varint,6,opt,name=duration_nanos,json=durationNanos,proto3,oneof"`
}

type Arg_StreamIds struct {
	// stream_ids is the id slot: the coordinator has resolved the selector and
	// partitioned the ids by owner, so each peer receives only its own.
	StreamIds *StreamIDs `protobuf:"bytes,7,opt,name=stream_ids,json=streamIds,proto3,oneof"`
}

func (*Arg_Text) isArg_Value() {}

func (*Arg_Integer) isArg_Value() {}

func (*Arg_Level) isArg_Value() {}

func (*Arg_Number) isArg_Value() {}

func (*Arg_TimeUnixNano) isArg_Value() {}

func (*Arg_DurationNanos) isArg_Value() {}

func (*Arg_StreamIds) isArg_Value() {}

type StreamIDs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamIDs) Reset() {
	*x = StreamIDs{}
	mi := &file_logagg_v1_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamIDs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamIDs) ProtoMessage() {}

func (x *StreamIDs) ProtoReflect() protoreflect.Message {
	mi := &file_logagg_v1_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamIDs.ProtoReflect.Descriptor instead.
func (*StreamIDs) Descriptor() ([]byte, []int) {
	return file_logagg_v1_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *StreamIDs) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

// Statement is a parameterized SQL statement with its arguments.
type Statement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	Args          []*Arg                 `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Statement) Reset() {
	*x = Statement{}
	mi := &file_logagg_v1_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Statement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statement) ProtoMessage() {}

func (x *Statement) ProtoReflect() protoreflect.Message {
	mi := &file_logagg_v1_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statement.ProtoReflect.Descriptor instead.
func (*Statement) Descriptor() ([]byte, []int) {
	return file_logagg_v1_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *Statement) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *Statement) GetArgs() []*Arg {
	if x != nil {
		return x.Args
	}
	return nil
}

// ExecuteRequest asks a peer to run a planned logs statement.
type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Logs  *Statement             `protobuf:"bytes,1,opt,name=logs,proto3" json:"logs,omitempty"`
	// aggregate says whether rows are (bucket, value, by...) points or log
	// records, and by names the grouping columns in order.
	Aggregate     bool     `protobuf:"varint,2,opt,name=aggregate,proto3" json:"aggregate,omitempty"`
	By            []string `protobuf:"bytes,3,rep,name=by,proto3" json:"by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_logagg_v1_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logagg_v1_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_logagg_v1_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteRequest) GetLogs() *Statement {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *ExecuteRequest) GetAggregate() bool {
	if x != nil {
		return x.Aggregate
	}
	return false
}

func (x *ExecuteRequest) GetBy() []string {
	if x != nil {
		return x.By
	}
	return nil
}

// Record is one log row, with its stream id since a peer's rows span streams.
type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      int64                  `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	TimeUnixNano  int64                  `protobuf:"varint,2,opt,name=time_unix_nano,json=timeUnixNano,proto3" json:"time_unix_nano,omitempty"`
	Seq           int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Level         Level                  `protobuf:"varint,4,opt,name=level,proto3,enum=logagg.v1.Level" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	TraceId       []byte                 `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId        []byte                 `protobuf:"bytes,7,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,8,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_logagg_v1_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_logagg_v1_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_logagg_v1_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *Record) GetStreamId() int64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *Record) GetTimeUnixNano() int64 {
	if x != nil {
		return x.TimeUnixNano
	}
	return 0
}

func (x *Record) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Record) GetLevel() Level {
	if x != nil {
		return x.Level
	}
	return Level_LEVEL_UNSPECIFIED
}

func (x *Record) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Record) GetTraceId() []byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

func (x *Record) GetSpanId() []byte {
	if x != nil {
		return x.SpanId
	}
	return nil
}

func (x *Record) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Point is one bucket of one group in an aggregation.
type Point struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BucketUnixNano int64                  `protobuf:"varint,1,opt,name=bucket_unix_nano,json=bucketUnixNano,proto3" json:"bucket_unix_nano,omitempty"`
	Value          float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Labels         map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_logagg_v1_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_logagg_v1_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_logagg_v1_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *Point) GetBucketUnixNano() int64 {
	if x != nil {
		return x.BucketUnixNano
	}
	return 0
}

func (x *Point) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Point) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// ExecuteResponse carries either records or points, matching the request.
type ExecuteResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Records []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Points  []*Point               `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	// source is the relation the statement read, echoed for the response.
	Source        string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_logagg_v1_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logagg_v1_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_logagg_v1_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteResponse) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ExecuteResponse) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *ExecuteResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

var File_logagg_v1_cluster_proto protoreflect.FileDescriptor

const file_logagg_v1_cluster_proto_rawDesc = "" +
	"\n" +
	"\x17logagg/v1/cluster.proto\x12\tlogagg.v1\x1a\x16logagg/v1/ingest.proto\"\xfa\x01\n" +
	"\x03Arg\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12\x1a\n" +
	"\ainteger\x18\x02 \x01(\x03H\x00R\ainteger\x12\x16\n" +
	"\x05level\x18\x03 \x01(\x05H\x00R\x05level\x12\x18\n" +
	"\x06number\x18\x04 \x01(\x01H\x00R\x06number\x12&\n" +
	"\x0etime_unix_nano\x18\x05 \x01(\x03H\x00R\ftimeUnixNano\x12'\n" +
	"\x0eduration_nanos\x18\x06 \x01(\x03H\x00R\rdurationNanos\x125\n" +
	"\n" +
	"stream_ids\x18\a \x01(\v2\x14.logagg.v1.StreamIDsH\x00R\tstreamIdsB\a\n" +
	"\x05value\"\x1d\n" +
	"\tStreamIDs\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"A\n" +
	"\tStatement\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x12\"\n" +
	"\x04args\x18\x02 \x03(\v2\x0e.logagg.v1.ArgR\x04args\"h\n" +
	"\x0eExecuteRequest\x12(\n" +
	"\x04logs\x18\x01 \x01(\v2\x14.logagg.v1.StatementR\x04logs\x12\x1c\n" +
	"\taggregate\x18\x02 \x01(\bR\taggregate\x12\x0e\n" +
	"\x02by\x18\x03 \x03(\tR\x02by\"\xc5\x02\n" +
	"\x06Record\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\x03R\bstreamId\x12$\n" +
	"\x0etime_unix_nano\x18\x02 \x01(\x03R\ftimeUnixNano\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\x12&\n" +
	"\x05level\x18\x04 \x01(\x0e2\x10.logagg.v1.LevelR\x05level\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\fR\atraceId\x12\x17\n" +
	"\aspan_id\x18\a \x01(\fR\x06spanId\x125\n" +
	"\x06fields\x18\b \x03(\v2\x1d.logagg.v1.Record.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb8\x01\n" +
	"\x05Point\x12(\n" +
	"\x10bucket_unix_nano\x18\x01 \x01(\x03R\x0ebucketUnixNano\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x124\n" +
	"\x06labels\x18\x03 \x03(\v2\x1c.logagg.v1.Point.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x80\x01\n" +
	"\x0fExecuteResponse\x12+\n" +
	"\arecords\x18\x01 \x03(\v2\x11.logagg.v1.RecordR\arecords\x12(\n" +
	"\x06points\x18\x02 \x03(\v2\x10.logagg.v1.PointR\x06points\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source2O\n" +
	"\vPeerService\x12@\n" +
	"\aExecute\x12\x19.logagg.v1.ExecuteRequest\x1a\x1a.logagg.v1.ExecuteResponseBEZCgithub.com/jamespolk/go-log-aggregator/api/proto/logagg/v1;logaggv1b\x06proto3"

var (
	file_logagg_v1_cluster_proto_rawDescOnce sync.Once
	file_logagg_v1_cluster_proto_rawDescData []byte
)

func file_logagg_v1_cluster_proto_rawDescGZIP() []byte {
	file_logagg_v1_cluster_proto_rawDescOnce.Do(func() {
		file_logagg_v1_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logagg_v1_cluster_proto_rawDesc), len(file_logagg_v1_cluster_proto_rawDesc)))
	})
	return file_logagg_v1_cluster_proto_rawDescData
}

var file_logagg_v1_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_logagg_v1_cluster_proto_goTypes = []any{
	(*Arg)(nil),             // 0: logagg.v1.Arg
	(*StreamIDs)(nil),       // 1: logagg.v1.StreamIDs
	(*Statement)(nil),       // 2: logagg.v1.Statement
	(*ExecuteRequest)(nil),  // 3: logagg.v1.ExecuteRequest
	(*Record)(nil),          // 4: logagg.v1.Record
	(*Point)(nil),           // 5: logagg.v1.Point
	(*ExecuteResponse)(nil), // 6: logagg.v1.ExecuteResponse
	nil,                     // 7: logagg.v1.Record.FieldsEntry
	nil,                     // 8: logagg.v1.Point.LabelsEntry
	(Level)(0),              // 9: logagg.v1.Level
}
var file_logagg_v1_cluster_proto_depIdxs = []int32{
	1, // 0: logagg.v1.Arg.stream_ids:type_name -> logagg.v1.StreamIDs
	0, // 1: logagg.v1.Statement.args:type_name -> logagg.v1.Arg
	2, // 2: logagg.v1.ExecuteRequest.logs:type_name -> logagg.v1.Statement
	9, // 3: logagg.v1.Record.level:type_name -> logagg.v1.Level
	7, // 4: logagg.v1.Record.fields:type_name -> logagg.v1.Record.FieldsEntry
	8, // 5: logagg.v1.Point.labels:type_name -> logagg.v1.Point.LabelsEntry
	4, // 6: logagg.v1.ExecuteResponse.records:type_name -> logagg.v1.Record
	5, // 7: logagg.v1.ExecuteResponse.points:type_name -> logagg.v1.Point
	3, // 8: logagg.v1.PeerService.Execute:input_type -> logagg.v1.ExecuteRequest
	6, // 9: logagg.v1.PeerService.Execute:output_type -> logagg.v1.ExecuteResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_logagg_v1_cluster_proto_init() }
func file_logagg_v1_cluster_proto_init() {
	if File_logagg_v1_cluster_proto != nil {
		return
	}
	file_logagg_v1_ingest_proto_init()
	file_logagg_v1_cluster_proto_msgTypes[0].OneofWrappers = []any{
		(*Arg_Text)(nil),
		(*Arg_Integer)(nil),
		(*Arg_Level)(nil),
		(*Arg_Number)(nil),
		(*Arg_TimeUnixNano)(nil),
		(*Arg_DurationNanos)(nil),
		(*Arg_StreamIds)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logagg_v1_cluster_proto_rawDesc), len(file_logagg_v1_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logagg_v1_cluster_proto_goTypes,
		DependencyIndexes: file_logagg_v1_cluster_proto_depIdxs,
		MessageInfos:      file_logagg_v1_cluster_proto_msgTypes,
	}.Build()
	File_logagg_v1_cluster_proto = out.File
	file_logagg_v1_cluster_proto_goTypes = nil
	file_logagg_v1_cluster_proto_depIdxs = nil
}
