// Wire format for collector <-> collector query fan-out.
//
// A coordinator parses and plans a query, resolves the matching streams, and
// asks each owning peer to answer for that peer's share of the stream ids. The
// request carries the query text and the request parameters, not SQL: the
// peer runs the same compiler over the same inputs, so the only statements a
// peer ever executes are ones its own planner wrote, with the time bound and
// row cap the planner always injects. A peer port is therefore never a way to
// run arbitrary SQL, whatever reaches it.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: logagg/v1/cluster.proto

package logaggv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecuteRequest asks a peer to answer one shard of a query.
type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// query is the DSL text the coordinator already parsed.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// The request half of the plan: the range, the row cap the coordinator
	// wants back from this shard, and the order.
	StartUnixNano int64 `protobuf:"varint,2,opt,name=start_unix_nano,json=startUnixNano,proto3" json:"start_unix_nano,omitempty"`
	EndUnixNano   int64 `protobuf:"varint,3,opt,name=end_unix_nano,json=endUnixNano,proto3" json:"end_unix_nano,omitempty"`
	Limit         int32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Forward       bool  `protobuf:"varint,5,opt,name=forward,proto3" json:"forward,omitempty"`
	// stream_ids is this peer's share of the resolved selector.
	StreamIds     []int64 `protobuf:"varint,6,rep,packed,name=stream_ids,json=streamIds,proto3" json:"stream_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_logagg_v1_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logagg_v1_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_logagg_v1_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ExecuteRequest) GetStartUnixNano() int64 {
	if x != nil {
		return x.StartUnixNano
	}
	return 0
}

func (x *ExecuteRequest) GetEndUnixNano() int64 {
	if x != nil {
		return x.EndUnixNano
	}
	return 0
}

func (x *ExecuteRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ExecuteRequest) GetForward() bool {
	if x != nil {
		return x.Forward
	}
	return false
}

func (x *ExecuteRequest) GetStreamIds() []int64 {
	if x != nil {
		return x.StreamIds
	}
	return nil
}

// Record is one log row, with its stream id since a peer's rows span streams.
type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      int64                  `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	TimeUnixNano  int64                  `protobuf:"varint,2,opt,name=time_unix_nano,json=timeUnixNano,proto3" json:"time_unix_nano,omitempty"`
	Seq           int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Level         Level                  `protobuf:"varint,4,opt,name=level,proto3,enum=logagg.v1.Level" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	TraceId       []byte                 `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId        []byte                 `protobuf:"bytes,7,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,8,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_logagg_v1_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_logagg_v1_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_logagg_v1_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *Record) GetStreamId() int64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *Record) GetTimeUnixNano() int64 {
	if x != nil {
		return x.TimeUnixNano
	}
	return 0
}

func (x *Record) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Record) GetLevel() Level {
	if x != nil {
		return x.Level
	}
	return Level_LEVEL_UNSPECIFIED
}

func (x *Record) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Record) GetTraceId() []byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

func (x *Record) GetSpanId() []byte {
	if x != nil {
		return x.SpanId
	}
	return nil
}

func (x *Record) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Point is one bucket of one group in an aggregation.
type Point struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BucketUnixNano int64                  `protobuf:"varint,1,opt,name=bucket_unix_nano,json=bucketUnixNano,proto3" json:"bucket_unix_nano,omitempty"`
	Value          float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Labels         map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_logagg_v1_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_logagg_v1_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_logagg_v1_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *Point) GetBucketUnixNano() int64 {
	if x != nil {
		return x.BucketUnixNano
	}
	return 0
}

func (x *Point) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Point) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// ExecuteResponse carries either records or points, matching the query.
type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Points        []*Point               `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_logagg_v1_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logagg_v1_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_logagg_v1_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteResponse) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ExecuteResponse) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

var File_logagg_v1_cluster_proto protoreflect.FileDescriptor

const file_logagg_v1_cluster_proto_rawDesc = "" +
	"\n" +
	"\x17logagg/v1/cluster.proto\x12\tlogagg.v1\x1a\x16logagg/v1/ingest.proto\"\xc1\x01\n" +
	"\x0eExecuteRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12&\n" +
	"\x0fstart_unix_nano\x18\x02 \x01(\x03R\rstartUnixNano\x12\"\n" +
	"\rend_unix_nano\x18\x03 \x01(\x03R\vendUnixNano\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x18\n" +
	"\aforward\x18\x05 \x01(\bR\aforward\x12\x1d\n" +
	"\n" +
	"stream_ids\x18\x06 \x03(\x03R\tstreamIds\"\xc5\x02\n" +
	"\x06Record\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\x03R\bstreamId\x12$\n" +
	"\x0etime_unix_nano\x18\x02 \x01(\x03R\ftimeUnixNano\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\x12&\n" +
	"\x05level\x18\x04 \x01(\x0e2\x10.logagg.v1.LevelR\x05level\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\fR\atraceId\x12\x17\n" +
	"\aspan_id\x18\a \x01(\fR\x06spanId\x125\n" +
	"\x06fields\x18\b \x03(\v2\x1d.logagg.v1.Record.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb8\x01\n" +
	"\x05Point\x12(\n" +
	"\x10bucket_unix_nano\x18\x01 \x01(\x03R\x0ebucketUnixNano\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x124\n" +
	"\x06labels\x18\x03 \x03(\v2\x1c.logagg.v1.Point.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"h\n" +
	"\x0fExecuteResponse\x12+\n" +
	"\arecords\x18\x01 \x03(\v2\x11.logagg.v1.RecordR\arecords\x12(\n" +
	"\x06points\x18\x02 \x03(\v2\x10.logagg.v1.PointR\x06points2O\n" +
	"\vPeerService\x12@\n" +
	"\aExecute\x12\x19.logagg.v1.ExecuteRequest\x1a\x1a.logagg.v1.ExecuteResponseBEZCgithub.com/jamespolk/go-log-aggregator/api/proto/logagg/v1;logaggv1b\x06proto3"

var (
	file_logagg_v1_cluster_proto_rawDescOnce sync.Once
	file_logagg_v1_cluster_proto_rawDescData []byte
)

func file_logagg_v1_cluster_proto_rawDescGZIP() []byte {
	file_logagg_v1_cluster_proto_rawDescOnce.Do(func() {
		file_logagg_v1_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logagg_v1_cluster_proto_rawDesc), len(file_logagg_v1_cluster_proto_rawDesc)))
	})
	return file_logagg_v1_cluster_proto_rawDescData
}

var file_logagg_v1_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_logagg_v1_cluster_proto_goTypes = []any{
	(*ExecuteRequest)(nil),  // 0: logagg.v1.ExecuteRequest
	(*Record)(nil),          // 1: logagg.v1.Record
	(*Point)(nil),           // 2: logagg.v1.Point
	(*ExecuteResponse)(nil), // 3: logagg.v1.ExecuteResponse
	nil,                     // 4: logagg.v1.Record.FieldsEntry
	nil,                     // 5: logagg.v1.Point.LabelsEntry
	(Level)(0),              // 6: logagg.v1.Level
}
var file_logagg_v1_cluster_proto_depIdxs = []int32{
	6, // 0: logagg.v1.Record.level:type_name -> logagg.v1.Level
	4, // 1: logagg.v1.Record.fields:type_name -> logagg.v1.Record.FieldsEntry
	5, // 2: logagg.v1.Point.labels:type_name -> logagg.v1.Point.LabelsEntry
	1, // 3: logagg.v1.ExecuteResponse.records:type_name -> logagg.v1.Record
	2, // 4: logagg.v1.ExecuteResponse.points:type_name -> logagg.v1.Point
	0, // 5: logagg.v1.PeerService.Execute:input_type -> logagg.v1.ExecuteRequest
	3, // 6: logagg.v1.PeerService.Execute:output_type -> logagg.v1.ExecuteResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_logagg_v1_cluster_proto_init() }
func file_logagg_v1_cluster_proto_init() {
	if File_logagg_v1_cluster_proto != nil {
		return
	}
	file_logagg_v1_ingest_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logagg_v1_cluster_proto_rawDesc), len(file_logagg_v1_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logagg_v1_cluster_proto_goTypes,
		DependencyIndexes: file_logagg_v1_cluster_proto_depIdxs,
		MessageInfos:      file_logagg_v1_cluster_proto_msgTypes,
	}.Build()
	File_logagg_v1_cluster_proto = out.File
	file_logagg_v1_cluster_proto_goTypes = nil
	file_logagg_v1_cluster_proto_depIdxs = nil
}
