// Wire format for agent -> collector log shipping.
//
// Design notes that matter for the rest of the system:
//
//   - Records are grouped into a batch that carries the label set once. Identical
//     label sets collapse to one stream_id at the collector (see internal/model),
//     so repeating labels per record would be pure wire overhead.
//   - Timestamps are int64 unix nanoseconds rather than google.protobuf.Timestamp:
//     one scalar instead of a heap-allocated message per record, on the hottest
//     path in the project.
//   - Levels are an enum, stored as SMALLINT. Never a free-text level column.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: logagg/v1/ingest.proto

package logaggv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Level is the severity of a record. Values are stable: they are persisted as
// integers in the logs table, so they may be appended to but never renumbered.
type Level int32

const (
	Level_LEVEL_UNSPECIFIED Level = 0
	Level_LEVEL_TRACE       Level = 1
	Level_LEVEL_DEBUG       Level = 2
	Level_LEVEL_INFO        Level = 3
	Level_LEVEL_WARN        Level = 4
	Level_LEVEL_ERROR       Level = 5
	Level_LEVEL_FATAL       Level = 6
)

// Enum value maps for Level.
var (
	Level_name = map[int32]string{
		0: "LEVEL_UNSPECIFIED",
		1: "LEVEL_TRACE",
		2: "LEVEL_DEBUG",
		3: "LEVEL_INFO",
		4: "LEVEL_WARN",
		5: "LEVEL_ERROR",
		6: "LEVEL_FATAL",
	}
	Level_value = map[string]int32{
		"LEVEL_UNSPECIFIED": 0,
		"LEVEL_TRACE":       1,
		"LEVEL_DEBUG":       2,
		"LEVEL_INFO":        3,
		"LEVEL_WARN":        4,
		"LEVEL_ERROR":       5,
		"LEVEL_FATAL":       6,
	}
)

func (x Level) Enum() *Level {
	p := new(Level)
	*p = x
	return p
}

func (x Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Level) Descriptor() protoreflect.EnumDescriptor {
	return file_logagg_v1_ingest_proto_enumTypes[0].Descriptor()
}

func (Level) Type() protoreflect.EnumType {
	return &file_logagg_v1_ingest_proto_enumTypes[0]
}

func (x Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Level.Descriptor instead.
func (Level) EnumDescriptor() ([]byte, []int) {
	return file_logagg_v1_ingest_proto_rawDescGZIP(), []int{0}
}

// AckCode reports what the collector did with a batch.
type AckCode int32

const (
	AckCode_ACK_CODE_UNSPECIFIED AckCode = 0
	// Accepted and durably queued. The agent may drop the batch.
	AckCode_ACK_CODE_ACCEPTED AckCode = 1
	// Rejected because the collector is saturated. Retryable: back off and resend.
	AckCode_ACK_CODE_OVERLOADED AckCode = 2
	// Rejected because the batch is malformed. Not retryable: resending the same
	// bytes will fail identically, so the agent must drop and count it.
	AckCode_ACK_CODE_INVALID AckCode = 3
	// Rejected because of a collector-side fault. Retryable.
	AckCode_ACK_CODE_INTERNAL AckCode = 4
)

// Enum value maps for AckCode.
var (
	AckCode_name = map[int32]string{
		0: "ACK_CODE_UNSPECIFIED",
		1: "ACK_CODE_ACCEPTED",
		2: "ACK_CODE_OVERLOADED",
		3: "ACK_CODE_INVALID",
		4: "ACK_CODE_INTERNAL",
	}
	AckCode_value = map[string]int32{
		"ACK_CODE_UNSPECIFIED": 0,
		"ACK_CODE_ACCEPTED":    1,
		"ACK_CODE_OVERLOADED":  2,
		"ACK_CODE_INVALID":     3,
		"ACK_CODE_INTERNAL":    4,
	}
)

func (x AckCode) Enum() *AckCode {
	p := new(AckCode)
	*p = x
	return p
}

func (x AckCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckCode) Descriptor() protoreflect.EnumDescriptor {
	return file_logagg_v1_ingest_proto_enumTypes[1].Descriptor()
}

func (AckCode) Type() protoreflect.EnumType {
	return &file_logagg_v1_ingest_proto_enumTypes[1]
}

func (x AckCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckCode.Descriptor instead.
func (AckCode) EnumDescriptor() ([]byte, []int) {
	return file_logagg_v1_ingest_proto_rawDescGZIP(), []int{1}
}

// LabelSet identifies the stream a batch belongs to.
//
// service, host and env are promoted to their own fields because every query
// filters on them and they become real columns; everything else lives in the
// extra map and is stored as JSONB.
type LabelSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Env           string                 `protobuf:"bytes,3,opt,name=env,proto3" json:"env,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,4,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelSet) Reset() {
	*x = LabelSet{}
	mi := &file_logagg_v1_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelSet) ProtoMessage() {}

func (x *LabelSet) ProtoReflect() protoreflect.Message {
	mi := &file_logagg_v1_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelSet.ProtoReflect.Descriptor instead.
func (*LabelSet) Descriptor() ([]byte, []int) {
	return file_logagg_v1_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *LabelSet) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LabelSet) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *LabelSet) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *LabelSet) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

// LogRecord is a single log line.
type LogRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Nanoseconds since the Unix epoch, UTC. Assigned by the agent at read time.
	TimeUnixNano int64 `protobuf:"varint,1,opt,name=time_unix_nano,json=timeUnixNano,proto3" json:"time_unix_nano,omitempty"`
	// Monotonic per-stream counter assigned by the agent. Together with the
	// stream and the timestamp this forms the storage dedup key, which is what
	// makes at-least-once delivery safe to replay.
	Seq     int64  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Level   Level  `protobuf:"varint,3,opt,name=level,proto3,enum=logagg.v1.Level" json:"level,omitempty"`
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// Raw 16-byte trace ID and 8-byte span ID, empty when absent. Bytes rather
	// than hex strings: half the wire size and half the storage.
	TraceId []byte `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId  []byte `protobuf:"bytes,6,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	// Extracted structured fields. String-valued on purpose: agents extract from
	// text, and typed JSON would make the same key arrive as a number from one
	// agent and a string from another.
	Fields        map[string]string `protobuf:"bytes,7,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRecord) Reset() {
	*x = LogRecord{}
	mi := &file_logagg_v1_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRecord) ProtoMessage() {}

func (x *LogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_logagg_v1_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRecord.ProtoReflect.Descriptor instead.
func (*LogRecord) Descriptor() ([]byte, []int) {
	return file_logagg_v1_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *LogRecord) GetTimeUnixNano() int64 {
	if x != nil {
		return x.TimeUnixNano
	}
	return 0
}

func (x *LogRecord) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *LogRecord) GetLevel() Level {
	if x != nil {
		return x.Level
	}
	return Level_LEVEL_UNSPECIFIED
}

func (x *LogRecord) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogRecord) GetTraceId() []byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

func (x *LogRecord) GetSpanId() []byte {
	if x != nil {
		return x.SpanId
	}
	return nil
}

func (x *LogRecord) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// LogBatch is one shipment: a label set plus the records observed for it.
type LogBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent-assigned identifier, unique per connection, echoed back in the Ack so
	// the agent knows which batch it may drop from its spool.
	BatchId string       `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Labels  *LabelSet    `protobuf:"bytes,2,opt,name=labels,proto3" json:"labels,omitempty"`
	Records []*LogRecord `protobuf:"bytes,3,rep,name=records,proto3" json:"records,omitempty"`
	// W3C trace context (traceparent, tracestate) of the agent's ship span. It
	// travels in the message because a bidirectional stream has no per-message
	// metadata; the collector's ingest span becomes this span's child.
	TraceContext  map[string]string `protobuf:"bytes,4,rep,name=trace_context,json=traceContext,proto3" json:"trace_context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogBatch) Reset() {
	*x = LogBatch{}
	mi := &file_logagg_v1_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogBatch) ProtoMessage() {}

func (x *LogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_logagg_v1_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogBatch.ProtoReflect.Descriptor instead.
func (*LogBatch) Descriptor() ([]byte, []int) {
	return file_logagg_v1_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *LogBatch) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *LogBatch) GetLabels() *LabelSet {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *LogBatch) GetRecords() []*LogRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *LogBatch) GetTraceContext() map[string]string {
	if x != nil {
		return x.TraceContext
	}
	return nil
}

// Ack is the collector's response for one batch.
type Ack struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	BatchId string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Code    AckCode                `protobuf:"varint,2,opt,name=code,proto3,enum=logagg.v1.AckCode" json:"code,omitempty"`
	// Records durably accepted. May be fewer than were sent when individual
	// records were rejected by validation.
	Accepted uint32 `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// Records rejected. accepted + rejected always equals the batch size.
	Rejected uint32 `protobuf:"varint,4,opt,name=rejected,proto3" json:"rejected,omitempty"`
	// Human-readable detail, set only when code is not ACK_CODE_ACCEPTED. Never
	// parsed by the agent; code carries the decision.
	Detail        string `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_logagg_v1_ingest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_logagg_v1_ingest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_logagg_v1_ingest_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *Ack) GetCode() AckCode {
	if x != nil {
		return x.Code
	}
	return AckCode_ACK_CODE_UNSPECIFIED
}

func (x *Ack) GetAccepted() uint32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *Ack) GetRejected() uint32 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

func (x *Ack) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_logagg_v1_ingest_proto protoreflect.FileDescriptor

const file_logagg_v1_ingest_proto_rawDesc = "" +
	"\n" +
	"\x16logagg/v1/ingest.proto\x12\tlogagg.v1\"\xba\x01\n" +
	"\bLabelSet\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x10\n" +
	"\x03env\x18\x03 \x01(\tR\x03env\x124\n" +
	"\x05extra\x18\x04 \x03(\v2\x1e.logagg.v1.LabelSet.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xae\x02\n" +
	"\tLogRecord\x12$\n" +
	"\x0etime_unix_nano\x18\x01 \x01(\x03R\ftimeUnixNano\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\x12&\n" +
	"\x05level\x18\x03 \x01(\x0e2\x10.logagg.v1.LevelR\x05level\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\fR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x06 \x01(\fR\x06spanId\x128\n" +
	"\x06fields\x18\a \x03(\v2 .logagg.v1.LogRecord.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x02\n" +
	"\bLogBatch\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12+\n" +
	"\x06labels\x18\x02 \x01(\v2\x13.logagg.v1.LabelSetR\x06labels\x12.\n" +
	"\arecords\x18\x03 \x03(\v2\x14.logagg.v1.LogRecordR\arecords\x12J\n" +
	"\rtrace_context\x18\x04 \x03(\v2%.logagg.v1.LogBatch.TraceContextEntryR\ftraceContext\x1a?\n" +
	"\x11TraceContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x98\x01\n" +
	"\x03Ack\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12&\n" +
	"\x04code\x18\x02 \x01(\x0e2\x12.logagg.v1.AckCodeR\x04code\x12\x1a\n" +
	"\baccepted\x18\x03 \x01(\rR\baccepted\x12\x1a\n" +
	"\brejected\x18\x04 \x01(\rR\brejected\x12\x16\n" +
	"\x06detail\x18\x05 \x01(\tR\x06detail*\x82\x01\n" +
	"\x05Level\x12\x15\n" +
	"\x11LEVEL_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vLEVEL_TRACE\x10\x01\x12\x0f\n" +
	"\vLEVEL_DEBUG\x10\x02\x12\x0e\n" +
	"\n" +
	"LEVEL_INFO\x10\x03\x12\x0e\n" +
	"\n" +
	"LEVEL_WARN\x10\x04\x12\x0f\n" +
	"\vLEVEL_ERROR\x10\x05\x12\x0f\n" +
	"\vLEVEL_FATAL\x10\x06*\x80\x01\n" +
	"\aAckCode\x12\x18\n" +
	"\x14ACK_CODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ACK_CODE_ACCEPTED\x10\x01\x12\x17\n" +
	"\x13ACK_CODE_OVERLOADED\x10\x02\x12\x14\n" +
	"\x10ACK_CODE_INVALID\x10\x03\x12\x15\n" +
	"\x11ACK_CODE_INTERNAL\x10\x042?\n" +
	"\n" +
	"LogService\x121\n" +
	"\x06Stream\x12\x13.logagg.v1.LogBatch\x1a\x0e.logagg.v1.Ack(\x010\x01BEZCgithub.com/jamespolk/go-log-aggregator/api/proto/logagg/v1;logaggv1b\x06proto3"

var (
	file_logagg_v1_ingest_proto_rawDescOnce sync.Once
	file_logagg_v1_ingest_proto_rawDescData []byte
)

func file_logagg_v1_ingest_proto_rawDescGZIP() []byte {
	file_logagg_v1_ingest_proto_rawDescOnce.Do(func() {
		file_logagg_v1_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logagg_v1_ingest_proto_rawDesc), len(file_logagg_v1_ingest_proto_rawDesc)))
	})
	return file_logagg_v1_ingest_proto_rawDescData
}

var file_logagg_v1_ingest_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_logagg_v1_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_logagg_v1_ingest_proto_goTypes = []any{
	(Level)(0),        // 0: logagg.v1.Level
	(AckCode)(0),      // 1: logagg.v1.AckCode
	(*LabelSet)(nil),  // 2: logagg.v1.LabelSet
	(*LogRecord)(nil), // 3: logagg.v1.LogRecord
	(*LogBatch)(nil),  // 4: logagg.v1.LogBatch
	(*Ack)(nil),       // 5: logagg.v1.Ack
	nil,               // 6: logagg.v1.LabelSet.ExtraEntry
	nil,               // 7: logagg.v1.LogRecord.FieldsEntry
	nil,               // 8: logagg.v1.LogBatch.TraceContextEntry
}
var file_logagg_v1_ingest_proto_depIdxs = []int32{
	6, // 0: logagg.v1.LabelSet.extra:type_name -> logagg.v1.LabelSet.ExtraEntry
	0, // 1: logagg.v1.LogRecord.level:type_name -> logagg.v1.Level
	7, // 2: logagg.v1.LogRecord.fields:type_name -> logagg.v1.LogRecord.FieldsEntry
	2, // 3: logagg.v1.LogBatch.labels:type_name -> logagg.v1.LabelSet
	3, // 4: logagg.v1.LogBatch.records:type_name -> logagg.v1.LogRecord
	8, // 5: logagg.v1.LogBatch.trace_context:type_name -> logagg.v1.LogBatch.TraceContextEntry
	1, // 6: logagg.v1.Ack.code:type_name -> logagg.v1.AckCode
	4, // 7: logagg.v1.LogService.Stream:input_type -> logagg.v1.LogBatch
	5, // 8: logagg.v1.LogService.Stream:output_type -> logagg.v1.Ack
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_logagg_v1_ingest_proto_init() }
func file_logagg_v1_ingest_proto_init() {
	if File_logagg_v1_ingest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logagg_v1_ingest_proto_rawDesc), len(file_logagg_v1_ingest_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logagg_v1_ingest_proto_goTypes,
		DependencyIndexes: file_logagg_v1_ingest_proto_depIdxs,
		EnumInfos:         file_logagg_v1_ingest_proto_enumTypes,
		MessageInfos:      file_logagg_v1_ingest_proto_msgTypes,
	}.Build()
	File_logagg_v1_ingest_proto = out.File
	file_logagg_v1_ingest_proto_goTypes = nil
	file_logagg_v1_ingest_proto_depIdxs = nil
}
