-- Base schema: the stream dimension table and the logs hypertable.
--
-- The shape here is the one decision that is expensive to change later, so the
-- reasoning is recorded inline as well as in .aidocs/decisions/ADR-0002.

CREATE EXTENSION IF NOT EXISTS timescaledb;

-- Label sets are deduplicated into their own table. The alternative -- a JSONB
-- label blob on every log row -- would repeat the same few hundred bytes across
-- millions of rows and force every selector to scan the hot table.
CREATE TABLE streams (
    -- xxhash64 of the canonical label encoding, reinterpreted as signed because
    -- Postgres has no unsigned 64-bit integer. Generated by the collector, not by
    -- a sequence: the same label set must produce the same ID on every node,
    -- with no coordination.
    stream_id  BIGINT      PRIMARY KEY,
    -- Promoted out of labels because every query filters on them.
    service    TEXT        NOT NULL,
    host       TEXT        NOT NULL,
    env        TEXT        NOT NULL,
    -- Everything else. Never contains service/host/env; the model rejects those
    -- as reserved so a selector can never be ambiguous.
    labels     JSONB       NOT NULL,
    first_seen TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX streams_service_env_idx ON streams (service, env);

-- jsonb_path_ops rather than the default jsonb_ops: it indexes whole key/value
-- paths instead of keys and values separately, which makes the index roughly half
-- the size and containment lookups faster. The tradeoff is that key-existence
-- queries (labels ? 'region') cannot use it -- and the DSL only ever generates
-- containment (labels @> '{"region":"eu"}'), so nothing is lost.
CREATE INDEX streams_labels_idx ON streams USING GIN (labels jsonb_path_ops);

CREATE TABLE logs (
    time      TIMESTAMPTZ NOT NULL,
    stream_id BIGINT      NOT NULL REFERENCES streams (stream_id),
    -- Agent-assigned monotonic counter, part of the dedup key below.
    seq       BIGINT      NOT NULL,
    -- Severity as an integer, matching model.Level. A TEXT level column would
    -- cost 5-8 bytes per row and make level>='warn' a lookup instead of a
    -- comparison.
    level     SMALLINT    NOT NULL,
    message   TEXT        NOT NULL,
    -- Raw bytes, not hex text: 16 and 8 bytes instead of 32 and 16.
    trace_id  BYTEA,
    span_id   BYTEA,
    fields    JSONB
);

-- by_range is the current dimension-builder API (create_hypertable's old
-- positional signature is deprecated). A 1 hour chunk interval is a starting
-- point chosen so recent chunks and their indexes stay in memory under the
-- benchmark load; phase 8 measures it and this comment gets a number.
--
-- No space partitioning: Timescale recommends against hash-partitioning a
-- single-node hypertable, and compress_segmentby in 0002 provides the same
-- per-stream locality without the extra chunk count.
SELECT create_hypertable('logs', by_range('time', INTERVAL '1 hour'));

-- The dedup key that makes at-least-once delivery safe. A crash between the
-- Timescale write and the JetStream ack causes redelivery, and the writer's
-- staging-table insert relies on this index to turn the replay into a no-op.
--
-- Timescale requires the partitioning column in every unique index on a
-- hypertable, which is why this is (stream_id, seq, time) and not (stream_id, seq).
-- The practical consequence: dedup only holds for a record replayed with an
-- identical timestamp. That is exactly the redelivery case, since the agent
-- assigns the timestamp once and spools it.
CREATE UNIQUE INDEX logs_dedup ON logs (stream_id, seq, time);

-- Serves the common "recent errors across everything" query without touching the
-- streams table. time DESC matches the default query direction so the planner can
-- stop at LIMIT rather than sorting.
CREATE INDEX logs_time_level ON logs (time DESC, level);
